namespace ProjectAegis.AI.Models.Types
{
    public enum ParameterType
    {
        Attack = 0,
        Skill = 1,
        Say = 2,
        ResetAggro = 3,
        ExecTrigger = 4,
        RemoveTrigger = 5,
        EnableTrigger = 6,
        CreateTimer = 7,
        RemoveTimer = 8,
        Flee = 9,
        BeTaunted = 10,
        FadeTarget = 11,
        FageAggro = 12,
        Break = 13,
        ActiveSpawner = 14,
        SetCommmonData = 15,
        AddCommonData = 16,
        SummonMonster = 17,
        ChangePath = 18,
        PlayAction = 19,
        ReviseHistory = 20,
        SetHistory = 21,
        DeliverFactionPvpPoints = 22,
        CalcVar = 23,
        SummonMonster2 = 24,
        ChangePath2 = 25,
        Skill2 = 26,
        ActiveSpawner2 = 27,
        DeliverTask = 28,
        SummonMine = 29,
        SummonNpc = 30,
        DeliverRandomTaskInRegion = 31,
        DeliverRandomTaskInHateList = 32,
        ClearTowerTaskInRegion = 33,
        Num = 34,
    }
}